# Порог подозрительности (чем ниже, тем чувствительнее)
suspicion-threshold: 200.0

# Длительность одной сессии, в течение которой проверяются сломанные руды, в секундах
session-duration: 300

# Задержка между уведомлениями о подозрительных сессиях в секундах
notification-cooldown: 150

# Режим отладки (вывод сломанных блоков игроками)
debug: false

# Сообщения
messages:
  suspicion-alert: "&c[SDAXR] ⚠ Подозрение на XRay: &6{player} &7добыл подозрительное количество руд!"
  no-permission: "&c[SDAXR] У вас нет прав для использования этой команды!"
  reload-success: "&a[SDAXR] Конфигурация перезагружена!"